### ISSUE TITLE
Application getting crashed every time on pre- lollipop devices.

### ISSUE THREAD

**Issue by KumariAnjuThakur** [spinaki/android-camera#5]
Hi,
I  Have tried sample project and this is working fine on >= Lollipop devices but , application always crashed on pre-lollipop devices. here are I am attaching logs for that:
FATAL EXCEPTION: main
                                                   Process: xyz.pinaki.androidcamera.example, PID: 15232
                                                   java.lang.VerifyError: xyz/pinaki/android/camera/CenteredCameraPreviewHolder
                                                       at xyz.pinaki.android.camera.CameraFragment.createCenteredCameraPreview(CameraFragment.java:270)
                                                       at xyz.pinaki.android.camera.CameraFragment.access$600(CameraFragment.java:39)
                                                       at xyz.pinaki.android.camera.CameraFragment$1.onCameraOpen(CameraFragment.java:68)
                                                       at xyz.pinaki.android.camera.CameraHandlerThread$1$1.run(CameraHandlerThread.java:37)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5050)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by spinaki** [comment]
Thanks -- i havent seen this before. Will definitely take a look. Couple questions:
1. Are you using version 1.0.1 ?
2. What phone hardware are you using for pre-lollipop ?

**Comment by rohit-kadam** [comment]
Hi,

java.lang.VerifyError: xyz/pinaki/android/camera/CenteredCameraPreviewHolder

on pre lollipop devices

**Comment by assasinshark** [comment]
Same and using version 1.0.2

**Comment by spinaki** [comment]
OK -- i will take a look at this soon. What is the target and min sdk ? It will be helpful if you can post the stacktrace too.

**Comment by assasinshark** [comment]
min sdk is 16, target 25, tested on android emulator version 19 and 22, working on 22, stacktrace is same as posted by KumariAnjuThakur

> java.lang.VerifyError: xyz/pinaki/android/camera/CenteredCameraPreviewHolder
at xyz.pinaki.android.camera.CameraFragment.createCenteredCameraPreview(CameraFragment.java:270)
at xyz.pinaki.android.camera.CameraFragment.access$600(CameraFragment.java:39)
at xyz.pinaki.android.camera.CameraFragment$1.onCameraOpen(CameraFragment.java:68)
at xyz.pinaki.android.camera.CameraHandlerThread$1$1.run(CameraHandlerThread.java:37)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5050)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)

**Comment by spinaki** [comment]
Thanks -- I have never tested it on emulator since camera / sensors are usually part of a hardware. Will take a look.

**Comment by spinaki** [comment]
hi, I added a new V2 API -- with major fixes. Please see the readme. Can you please let me know if this bug still exists.

**Comment by spinaki** [comment]
closing since this probably has been fixed.
