### ISSUE TITLE
Shows white screen on Android 7

### ISSUE THREAD

**Issue by dah4oz** [spinaki/android-camera#8]
No camera preview is available, instead white screen is shown. If you try to change the camera it crashes.

**Comment by spinaki** [comment]
can you add the details plz: Android SDK versions (target and min), What phone model, What OS version on Phone and a stacktrace.

**Comment by dah4oz** [comment]
Nexus 5X, Android 7.1.2, minSdkVersion 16, targetSdkVersion 25

On starting the camera only white screen is show with two icons - take picture and switch camera. If you click switch camera app crashes with the following exception.

```
Process: com.megamallsofia.android, PID: 8077
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.hardware.camera2.CameraDevice.getId()' on a null object reference
                                                                             at xyz.pinaki.android.camera.Camera2Fragment.switchCamera(Camera2Fragment.java:302)
                                                                             at xyz.pinaki.android.camera.Camera2Fragment.access$100(Camera2Fragment.java:41)
                                                                             at xyz.pinaki.android.camera.Camera2Fragment$2.onClick(Camera2Fragment.java:120)
                                                                             at android.view.View.performClick(View.java:5637)
                                                                             at android.view.View$PerformClick.run(View.java:22429)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

**Comment by spinaki** [comment]
hi, I added a new V2 API -- with major fixes. Please see the readme. Can you please let me know if this bug still exists.

**Comment by spinaki** [comment]
closing since this probably has been fixed.
